artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source: metric_data/prometheus_metrics.csv
  feature_store: artifacts/data_ingestion/feature_store
  split_store: artifacts/data_ingestion/ingested
  local_data_file: artifacts/data_ingestion/feature_store/prometheus_metrics.csv
  train_data_time_interval: 2.25
  train_ingested_data: artifacts/data_ingestion/ingested/train_data.csv
  val_ingested_data: artifacts/data_ingestion/ingested/val_data.csv

data_validation:
  root_dir: artifacts/data_validation
  source_train_path: artifacts/data_ingestion/ingested/train_data.csv
  source_val_path: artifacts/data_ingestion/ingested/val_data.csv
  status: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  check_status: artifacts/data_validation/status.txt
  data_directory: artifacts/data_transformation/data
  object_directory: artifacts/data_transformation/object
  train_ingested_data: artifacts/data_ingestion/ingested/train_data.csv
  val_ingested_data: artifacts/data_ingestion/ingested/val_data.csv
  transformed_train_data: artifacts/data_transformation/data/transformed_train.csv
  transformed_val_data: artifacts/data_transformation/data/transformed_val.csv
  preprocessor_path: artifacts/data_transformation/object/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  model_directory: artifacts/model_trainer/model_parameters
  training_data: artifacts/data_transformation/data/transformed_train.csv
  validation_data: artifacts/data_transformation/data/transformed_val.csv
