{
 "title": "Advanced-Monitoring-System",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Anomaly Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "anomaly_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Is Anomaly",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "is_anomaly", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Available (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read (C)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{volume=\"C:\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Sent (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_sent_total{nic=\"TP-Link Wireless USB Adapter\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{nic=\"TP-Link Wireless USB Adapter\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write (C)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{volume=\"C:\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}